# Generated by Django 3.0.5 on 2020-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choicw_text',
            new_name='choice_text',
        ),
    ]
